#Capsule Workbench Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nlp-ingestion-status-web..name }}
  namespace: {{ .Values.nlp-ingestion-status-web.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nlp-ingestion-status-web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nlp-ingestion-status-web.name }}
    spec:
      containers:
        - name: {{ .Values.nlp-ingestion-status-web.name }}
          image: {{ .Values.nlp-ingestion-status-web.image }}
          # env:
          #   - name: BACK_END_BASE_PATH
          #     value: "http://{{ .Values.etl.service.name }}.{{ .Values.etl.namespace }}.svc.cluster.local:{{ .Values.etl.service.port }}/"
          # ports:
          #   - containerPort: {{ .Values.nlp-ingestion-status-web.port }}